/*
  ===========================================================================================
  TYPE DEFINITIONS & DATA SCHEMA ARCHITECTURE
  ===========================================================================================
  
  AGENCY DATABASE SCHEMA (POSTGRESQL):
  
  1. Table: `clients` (Tenants)
     - client_id: Integer [PK] (Auto Inc)
     - client_name: Varchar(100)
     - sector: Varchar(50)
     - whatsapp_id: Varchar(50) [UNIQUE] -> WABA ID used by n8n to route messages.
     - dify_api_key: Varchar(100) -> Auth key for the client's Dify App.
     - dashboard_config: JSONB -> UI Settings (Branding, Agent Identity).
     - is_active: Boolean [Default: true]
  
  2. Table: `whatsapp_log` (Message History)
     - log_id: Integer [PK] (Auto Inc)
     - client_id: Integer [FK -> clients.client_id]
     - phone: Varchar(20)
     - direction: Varchar(10) -> 'IN' (User) or 'OUT' (AI/Agent)
     - message_content: Text
     - sentiment_score: Varchar(20) -> 'Positive', 'Negative', 'Neutral' (Computed by Dify/N8N)
     - timestamp: Timestamp [Default: CURRENT_TIMESTAMP]
  
  3. MinIO Storage:
     - Bucket: `agency-assets`
     - Structure: `/{client_id}/{property_id}/{filename}`
*/

import React from 'react';

// --- DATABASE MODELS (Matches Postgres) ---

export interface AgencyClient {
  client_id: number;
  client_name: string;
  sector: string;
  whatsapp_id: string;
  dify_api_key: string;
  dashboard_config: AppSettings;
  is_active: boolean;
}

export interface WhatsAppLog {
  log_id: number;
  client_id: number;
  phone: string;
  direction: 'IN' | 'OUT';
  message_content: string;
  sentiment_score: string; 
  timestamp: string;
}

// --- FRONTEND TYPES ---

export enum LeadStatus {
  NEW = 'NEW',
  QUALIFIED = 'QUALIFIED',
  SITE_VISIT_SCHEDULED = 'SITE_VISIT',
  NEGOTIATION = 'NEGOTIATION',
  CLOSED = 'CLOSED',
  COLD = 'COLD',
  STOP_AI = 'STOP_AI'
}

export enum PropertyStatus {
  AVAILABLE = 'AVAILABLE',
  UNDER_OFFER = 'UNDER_OFFER',
  SOLD = 'SOLD'
}

export interface Lead {
  id: string;
  name: string;
  platform: 'Telegram' | 'WhatsApp' | 'Web' | 'Salesforce' | 'HubSpot';
  phone: string; // Aggregated from whatsapp_log
  budget: string;
  interestedIn: string[];
  status: LeadStatus;
  lastActive: string;
  conversationSummary: string; // Generated by Dify via `whatsapp_log` analysis
  confidenceScore: number;
  siteVisitTime?: string;
  chatHistory: { sender: 'user' | 'bot', text: string, timestamp: number }[]; // Derived from whatsapp_log
  priority?: 'HIGH' | 'MEDIUM' | 'LOW';
}

export interface PropertyMedia {
  id: string;
  type: 'image' | 'video';
  url: string; // MinIO Public URL
  file?: File;
}

export interface PropertyDocument {
  id: string;
  name: string;
  type: 'pdf' | 'text';
  content: string; 
  base64?: string;
  mimeType?: string;
  url?: string; // MinIO URL
}

export interface Property {
  id: string;
  title: string;
  location: string;
  price: string;
  bhk: string;
  bathrooms: string;
  furnishing: 'Fully Furnished' | 'Semi Furnished' | 'Unfurnished';
  type: string;
  size: string;
  status: PropertyStatus;
  description: string;
  features: string[];
  media: PropertyMedia[];
  documents: PropertyDocument[];
}

export interface ActivityLog {
  id: string;
  type: 'LEAD' | 'PROPERTY' | 'SYSTEM' | 'COMPLIANCE' | 'CRM';
  message: string;
  subtext: string;
  timestamp: Date;
  severity: 'info' | 'success' | 'warning' | 'danger';
}

export interface ChartData {
  label: string;
  leads: number;
  visits: number;
}

// Stored in `clients.dashboard_config` JSONB column
export interface AppSettings {
  appName: string;
  autoReply: boolean;
  minConfidenceThreshold: number;
  notificationEmail: string;
  enableAiBooking: boolean;
  workHoursStart: string;
  workHoursEnd: string;
  accentColor: string;
  workDays: number[]; 
  
  // Magic Draft Identity
  agentName: string;
  brokerageName: string;
  agentPhone: string;
  agentEmail: string;
  agentWebsite: string;
}

export interface BlockedTimeRule {
  id: string;
  title: string;
  startTime: string; 
  endTime: string;   
  isRecurring: boolean;
  recurrenceType?: 'DAILY' | 'WEEKLY' | 'MONTHLY';
  recurrenceDays?: number[]; 
}

export interface CalendarEvent {
  id: string;
  title: string;
  start: Date;
  end: Date;
  type: 'VISIT' | 'BLOCK' | 'HOLIDAY';
  attendees?: string[];
}

export interface ComplianceReport {
  id: string;
  fileName: string;
  score: number;
  flags: { severity: 'high' | 'medium' | 'low', text: string }[];
  summary: string;
}

export interface ScrapedListing {
  id: string;
  source: 'MagicBricks' | '99acres' | 'Housing' | 'NoBroker';
  title: string;
  location: string;
  price: string;
  ownerName: string;
  contact: string;
  url: string;
  predictedMotivation?: 'High' | 'Medium' | 'Low';
  matchingBuyerCount?: number;
}

export interface NavItem {
  id: string;
  label: string;
  icon: React.ElementType;
}

export interface BrandingConfig {
  appName: string;
  logoUrl?: string;
  themeColor: string;
}