import React from 'react';

export enum LeadStatus {
  NEW = 'NEW',
  QUALIFIED = 'QUALIFIED',
  SITE_VISIT_SCHEDULED = 'SITE_VISIT',
  NEGOTIATION = 'NEGOTIATION',
  CLOSED = 'CLOSED',
  COLD = 'COLD',
  STOP_AI = 'STOP_AI'
}

export enum PropertyStatus {
  AVAILABLE = 'AVAILABLE',
  UNDER_OFFER = 'UNDER_OFFER',
  SOLD = 'SOLD'
}

export interface Lead {
  id: string;
  name: string;
  platform: 'Telegram' | 'WhatsApp' | 'Web';
  phone: string;
  budget: string;
  interestedIn: string[]; // Array of Property IDs or strings
  status: LeadStatus;
  lastActive: string;
  conversationSummary: string; // Generated by AI
  confidenceScore: number; // 0-100
  chatHistory: { sender: 'user' | 'bot', text: string, timestamp: number }[];
}

export interface PropertyMedia {
  id: string;
  type: 'image' | 'video';
  url: string; // Blob URL for local files or Remote URL
  file?: File; // The actual file object
}

export interface PropertyDocument {
  id: string;
  name: string;
  type: 'pdf' | 'text';
  content: string; // Fallback text context
  base64?: string; // Actual file data for Gemini
  mimeType?: string;
  url?: string; // Blob URL
}

export interface Property {
  id: string;
  title: string;
  location: string;
  price: string;
  
  // Specific Real Estate Fields
  bhk: string; // e.g., '3', '4', 'Penthouse'
  bathrooms: string;
  furnishing: 'Fully Furnished' | 'Semi Furnished' | 'Unfurnished';
  type: string; // e.g. Apartment, Villa
  size: string; // e.g. 2400 sqft
  
  status: PropertyStatus;
  description: string;
  features: string[];
  
  // Multimedia & Docs
  media: PropertyMedia[];
  documents: PropertyDocument[];
}

export interface ActivityLog {
  id: string;
  type: 'LEAD' | 'PROPERTY' | 'SYSTEM';
  message: string;
  subtext: string;
  timestamp: Date;
  severity: 'info' | 'success' | 'warning' | 'danger';
}

export interface ChartData {
  label: string;
  leads: number;
  visits: number;
}

export interface AppSettings {
  appName: string;
  brokerName: string;
  autoReply: boolean;
  minConfidenceThreshold: number;
  notificationEmail: string;
}

export interface NavItem {
  id: string;
  label: string;
  icon: React.ElementType;
}